# yamllint disable-file
---
name: Installer Testing With Zapper CI
on: push
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: pre-commit
        run: |
          ls
          pwd
          sudo apt install -y pre-commit git
          pre-commit run --all-files
